[conf]
# Utils
utils = true # Need for Telescope and Icons :p
# Colors
colorschemes = true
# Status Lines
galaxy = false
lualine = false
express = true
# Completion
lsp = true
# Ide Completion
ide_tools = true
# Vim Script Development
vim_dev = true
# Fuzzy find
telescope = true
# Fast Movements
fast_movements = true
# Tree Sitter
tree_sitter = false
# Polygot
polygot = true
